# Generated by Django 5.0.1 on 2024-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
