# Generated by Django 5.0.1 on 2024-02-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0002_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
