# Generated by Django 5.0.1 on 2024-02-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0003_alter_error_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='data',
        ),
        migrations.AddField(
            model_name='error',
            name='error',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='error',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
