# Generated by Django 5.0.1 on 2024-02-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0004_remove_error_data_error_error_error_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='timestamp2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
