# Generated by Django 5.0.1 on 2024-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0005_error_timestamp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='timestamp2',
        ),
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
