# Generated by Django 5.0.1 on 2024-02-08 04:21

import django.db.models.deletion
import parsing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0006_remove_error_timestamp2_alter_error_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='error',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='error',
            name='url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=parsing_app.models.defaults_urls)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing_app.city', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing_app.language', verbose_name='Язык программирования')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
