# Generated by Django 5.0.1 on 2024-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0008_error_timestamp_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='timestamp_zone',
        ),
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
